import { Platform, StatusBar, StyleSheet } from "react-native";
import { RFValue as rf } from "react-native-responsive-fontsize";
import { getPercent } from "../../middleware";

//container Styles starts here
export const styles = ({ width, height }) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#FAFCFF",
    },
    balancecard: {
      height: getPercent(20, height),
      width: getPercent(90, width),
      borderRadius: 10,
      backgroundColor: "#0BA7FF",
      alignSelf: "center",
      marginVertical: 5,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: getPercent(3, width),
      overflow: "hidden",
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,

      elevation: 5,
    },
    directdebitbody: {
      height: getPercent(8, height),
      width: getPercent(90, width),
      borderRadius: 10,
      backgroundColor: "#FFA4B8",
      alignSelf: "center",
      marginVertical: 5,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: getPercent(3, width),
      overflow: "hidden",
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,

      elevation: 5,
    },
    transactionsbody: {
      height: getPercent(8, height),
      width: getPercent(90, width),
      borderRadius: 10,
      backgroundColor: "#E0E0E0",
      alignSelf: "center",
      marginVertical: 5,
      flexDirection: "row",
      alignItems: "center",
      // justifyContent: "space-between",
      paddingHorizontal: getPercent(3, width),
      overflow: "hidden",
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,

      elevation: 5,
    },
    fundsbody: {
      height: getPercent(8, height),
      width: getPercent(90, width),
      borderRadius: 10,
      backgroundColor: "#6FCF97",
      alignSelf: "center",
      marginVertical: 5,
      flexDirection: "row",
      alignItems: "center",
      // justifyContent: "space-between",
      paddingHorizontal: getPercent(3, width),
      overflow: "hidden",
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,

      elevation: 5,
    },
    group: {
      height: getPercent(8, height),
      width: getPercent(90, width),
      borderRadius: 10,
      backgroundColor: "#F2C94C",
      alignSelf: "center",
      marginVertical: 5,
      flexDirection: "row",
      alignItems: "center",
      // justifyContent: "space-between",
      paddingHorizontal: getPercent(3, width),
      overflow: "hidden",
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,

      elevation: 5,
    },
    cardtext: {
      fontFamily: "Medium",
      fontSize: rf(14),
      color: "#FFFDFD",
    },
    clams: {
      fontFamily: "Medium",
      fontSize: rf(14),
      color: "#FFFDFD",
    },
    background: {
      position: "absolute",
      height: getPercent(20, height),
      width: getPercent(90, width),
    },
    backgrounddebit: {
      position: "absolute",
      height: getPercent(10, height),
      width: getPercent(90, width),
    },
    iconbody: {
      height: getPercent(5, height),
      width: getPercent(5, height),
      borderRadius: 100,
      justifyContent: "center",
      alignItems: "center",
      overflow: "hidden",
    },
    funds: {
      position: "absolute",
      height: getPercent(5, height),
      width: getPercent(5, height),
    },
    fundstext: {
      fontFamily: "Medium",
      fontSize: rf(14),
      color: "#323F4B",
      marginLeft: 10,
    },
    invitewrapper: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: getPercent(5, width),
    },
    invite: {
      height: getPercent(8, height),
      width: getPercent(40, width),
      borderRadius: 10,
      backgroundColor: "#fff",
      alignSelf: "center",
      marginVertical: 5,
      flexDirection: "row",
      alignItems: "center",
      // justifyContent: "space-between",
      paddingHorizontal: getPercent(3, width),
      overflow: "hidden",
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,

      elevation: 5,
    },
    iconbodyinvite: {
      height: getPercent(5, height),
      width: getPercent(5, height),
      borderRadius: 100,
      justifyContent: "center",
      alignItems: "center",
      overflow: "hidden",
      backgroundColor: "#E5E8ED",
    },
  });
